// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "build/**",
      "dist/**",
      "dist-worker/**",
      "node_modules/**",
      // Generated by `vercel build` / `c8` — never our source, must not be linted.
      ".vercel/**",
      "coverage/**",
    ],
  },
  js.configs.recommended,
  {
    // Node build/dev scripts (ESM). Give them Node globals so no-undef doesn't
    // fire on URL, URLSearchParams, console, process, etc. They are tooling, not
    // shipped runtime code, so the stdout-hygiene no-console rule does not apply.
    files: ["scripts/**/*.{mjs,js}"],
    languageOptions: { globals: { ...globals.node } },
  },
  {
    files: ["src/**/*.ts"],
    extends: [...tseslint.configs.recommended],
    rules: {
      // stdout is the JSON-RPC stdio channel — only console.error is allowed
      // on the server path, mirroring the stdio-hygiene test.
      "no-console": ["error", { allow: ["error"] }],
    },
  },
  {
    // index.ts handles `--version` in CLI mode and exits before the stdio
    // transport starts, so console.log to stdout is intentional there.
    files: ["src/index.ts"],
    rules: { "no-console": ["error", { allow: ["error", "log"] }] },
  },
  // Disables ESLint formatting rules that would conflict with Prettier. Keep last.
  prettier,
);
