#!/usr/bin/env node
/**
 * Record the response fields the backend ACTUALLY returns, so the declared Zod schemas can
 * be checked against reality.
 *
 * WHY THIS EXISTS: `paperObject` in src/tools/_output.ts and `LEAN_FIELDS` in the backend's
 * api/routers/public.py are two hand-maintained field lists, in two separate repos, with
 * nothing linking them. They had already drifted when this was written on 2026-09-03:
 * paperObject declared 25 fields while the lean default returned 15. Nothing detected that,
 * because nothing compared them.
 *
 * WHY NOT GENERATE FROM OpenAPI: the backend does publish /v1/openapi.json, but the
 * endpoints that matter return bare dicts rather than response models, so the schema for
 * /v1/papers/search is literally {"type":"object","additionalProperties":true}. Until those
 * endpoints declare response models, OpenAPI cannot describe the paper shape, so observed
 * responses are the only available source of truth.
 *
 * This is a MANUAL sync, not a CI step — it needs the network and a live API. CI only
 * asserts that the committed fixture and the declared schema agree (see
 * src/__tests__/schema_drift.test.ts). Run it when you change a response shape, and before
 * a release:
 *
 *   node scripts/schema-sync.mjs                # anonymous probes only
 *   SF_API_KEY=sf_... node scripts/schema-sync.mjs   # also covers /library
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(
  __dirname,
  "../src/__tests__/fixtures/observed-fields.json",
);
const BASE =
  process.env.SF_API_BASE_URL ?? "https://api.scholarfeed.org/api/v1";
const KEY = process.env.SF_API_KEY;

// A browser-ish UA is REQUIRED: the Cloudflare WAF answers scripted user-agents with a
// 403 (Error 1010), which reads exactly like a dead endpoint.
const UA = "undici";

/**
 * One probe per (tool, envelope key). `auth` marks probes that cannot run anonymously.
 * Keep the queries boring and stable — this records shape, not results.
 */
const PROBES = [
  {
    tool: "search_papers",
    key: "papers",
    path: "/public/papers/search?q=language+model+agents&mode=semantic&limit=3",
  },
  {
    tool: "get_citations",
    key: "papers",
    path: "/public/papers/2503.08669/citations?direction=cited_by&limit=3",
  },
  {
    tool: "get_field_orientation",
    key: "papers",
    path: "/public/field-orientation?topic=retrieval+augmented+generation",
  },
  { tool: "list_library", key: "papers", path: "/library?limit=3", auth: true },
  { tool: "check_watches", key: "hits", path: "/watches/hits", auth: true },
];

async function probe({ tool, key, path, auth }) {
  if (auth && !KEY) {
    console.error(`  ${tool.padEnd(24)} SKIPPED (needs SF_API_KEY)`);
    return null;
  }
  const headers = { Accept: "application/json", "User-Agent": UA };
  if (KEY) headers.Authorization = `Bearer ${KEY}`;
  const res = await fetch(`${BASE}${path}`, { headers });
  if (!res.ok) {
    console.error(`  ${tool.padEnd(24)} HTTP ${res.status} — not recorded`);
    return null;
  }
  const body = await res.json();
  const rows = body?.[key];
  if (!Array.isArray(rows) || rows.length === 0) {
    console.error(`  ${tool.padEnd(24)} no rows under "${key}" — not recorded`);
    return null;
  }
  // Union across rows: a field absent from row 0 but present on row 2 is still returned.
  const fields = [...new Set(rows.flatMap((r) => Object.keys(r)))].sort();
  console.error(
    `  ${tool.padEnd(24)} ${String(rows.length).padStart(2)} rows, ${fields.length} fields under "${key}"`,
  );
  return { tool, envelopeKey: key, rows: rows.length, fields };
}

console.error(`Probing ${BASE}${KEY ? " (authenticated)" : " (anonymous)"}\n`);
const observed = [];
for (const p of PROBES) {
  const r = await probe(p);
  if (r) observed.push(r);
}

if (observed.length === 0) {
  console.error("\nNo probes succeeded — refusing to write an empty fixture.");
  process.exit(1);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  JSON.stringify(
    {
      _comment:
        "GENERATED by scripts/schema-sync.mjs — do not hand-edit. Records the fields the " +
        "backend actually returns, so src/__tests__/schema_drift.test.ts can check the " +
        "declared Zod schemas against reality. Re-run after any response-shape change.",
      syncedAt: new Date().toISOString().slice(0, 10),
      base: BASE,
      observed,
    },
    null,
    2,
  ) + "\n",
);
console.error(`\nWrote ${OUT}`);
